name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Step with 23f1000664@ds.study.iitm.ac.in"
        run: echo "This step is being checked by the grader!"

      - name: Second step
        run: echo "Hello, world!"
